### ISSUE TITLE
Animated stickers stop playing instead of looping

### ISSUE THREAD

**Issue by Nogooduser** [Pitu/Magane#4]
As the title says, animated stickers always stop playing when the gifs reach the end of their animation. I have auto play gifs enabled in the settings so that's not the issue either, and I've also tested sending other gifs I have laying around and they always keep looping nonstop, so it seems to be something in Magane's gifs that's affecting them in particular.

Both the stickers I send in chat as well as the ones in the menu always stop playing, and although it's not the worst thing ever it definitely is a little sad to not have the stickers play out as intended in chat, and it's also a bit annoying to not be able to immediately discern which stickers are animated in the menu, since they're all frozen after their first loop.

I'm not sure if this is an issue with Magane or Discord itself, but figured I'd report it just in case. If there's nothing that can be done then that's a shame.

I could also be completely missing the point and this could be intentional, if that's so then excuse my ignorance.

**Comment by BobbyWibowo** [comment]
It's not an issue with either Magane or Discord, but LINE itself. Magane hosts the stickers, but as far as I know, they were taken straight from the LINE store.
In LINE store, animated stickers are actually APNGs (Animate PNGs), and unfortunately they aren't set on infinite loop.
Take this sticker for example: https://stickershop.line-scdn.net/stickershop/v1/sticker/52526392/IOS/sticker_animation@2x.png;compress=true
That's straight from the LINE store, as you can tell by the domain, and it'll only play for a few moments before stopping permanently (at least until the page is refreshed).
It's just how it is in LINE. I got the same sticker in my LINE and it'll also stop playing after a while.

**Comment by Nogooduser** [comment]
Ahh, that explains it, thanks for clarifying. I guess I just have to get used to it then.

Though it would be really useful if Magane could somehow reset the animations whenever you open the stickers panel, because otherwise they're always frozen after the first time.

**Comment by Pitu** [comment]
Yeah this is quite challenging actually.
LINE provides animated PNGs which is some really obscure thing, so I locally convert them to gif before uploading to Magane but apparently they lose the loop property.

I'm currently converting them with [apng2gif](http://apng2gif.sourceforge.net) via console, so if someone comes up with a better solution that involves ffmpeg or some other tool I'll look into it.

**Comment by BobbyWibowo** [comment]
>I'm currently converting them with apng2gif via console, so if someone comes up with a better solution that involves ffmpeg or some other tool I'll look into it.

Well, this is a bit awkward. I tried `ffmpeg -i sticker.png sticker.gif` just now and it correctly gave out an infinite loop GIF of the animated PNG (I used the one I linked previously), without having to add any other extra options.

I built mine from source though, last I updated a month ago I think.

**Comment by Pitu** [comment]
Ok that definitely didn't work when I tried a few months ago, I'll try to update this weekend and see if the prebuilt binaries work now.

**Comment by emyarod** [comment]
resolved in https://github.com/Pitu/Magane-server/commit/21c9cf1edde33a6848f07928b3d988d6e03b733e
