### ISSUE TITLE
yarn install fails due to node-sass/node-gyp errors

### ISSUE THREAD

**Issue by emyarod** [Pitu/Magane#41]
ran `yarn install` to get my dev environment back up to date and ran into this issue https://github.com/sass/node-sass/issues/2868 on both macOS and Windows 10. Replacing the deprecated `node-sass` package with dart sass should resolve this

**Comment by Pitu** [comment]
Fixed in bf8a5d423eb4bb5eaa75da40ae2bcde87dc59cc9
