### ISSUE TITLE
Button disappears a little after showing up

### ISSUE THREAD

**Issue by Luffyyy** [Pitu/Magane#47]
Essentially when starting discord with BD, the stickers button will show only to disappear a second later. I was able to solve it by adding a delay to the start function in plugin script, but I assume there's a better way to fix it. Toggling the plugin works too.

**Comment by Shampo0oing** [comment]
@Luffyyy how did you delay the start function could you send an exemple ?

**Comment by Luffyyy** [comment]
> 
> 
> @Luffyyy how did you delay the start function could you send an exemple ?

Sure: 

```js
magane.prototype.start = function() {
    setTimeout(function() {
        // Try to unload first.
        magane.prototype.stop();
        const element = document.createElement('script');
        element.className = magane.prototype.vars.className;
        element.setAttribute('src', magane.prototype.vars.src);
        document.head.appendChild(element);
    }, 10000);
};
```

**Comment by Shampo0oing** [comment]
ty man it solved temporarly the problem. Hope a better solution will soon be found cause I have the same problem, wich persist event after disabling all my plugin that modified the input box.

**Comment by BobbyWibowo** [comment]
@Pitu this one specifically can already be closed since MaganeBD
