### ISSUE TITLE
 Cannot read property 'innerText' of null  at Y (App.svelte:359)

### ISSUE THREAD

**Issue by NawaNae** [Pitu/Magane#53]
at App.svelte:359
```js
document.querySelector('[class^=textArea-] span').innerText; 
```
the return value of querySelector is null

my discordCanary dom of textArea does not contain any span 
like
```html
<textarea ... class="textArea-2CLwUE fontSize16Padding-XoMpjI scrollbarGhostHairline-2LpzZ9 scrollbar-3vVt8d"></textarea>
```

so I am not sure if just change this line into 
```js
document.querySelector('[class^=textArea-]').innerText; 
```
can solve this problem or not

(I don't know how to debug this plugin sorry)

Thanks a lot

**Comment by BobbyWibowo** [comment]
Are you still encountering this issue? We have been unable to replicate this till date, even in Canary

**Comment by NawaNae** [comment]
I still encountered this issue in my canary, and I find the difference between Canary, PTB and Discord.
#### Env
Canary 124017 (2c2001f)
BetterDiscord 1.5.3

The message sending box (textarea) are using different element to implement
![image](https://user-images.githubusercontent.com/29101687/163383960-0130abe8-71a4-45fc-9549-9e008fcceb7d.png)

Canary
![image](https://user-images.githubusercontent.com/29101687/163385125-224bcec4-367e-4b8c-aa7b-d7fc2e503909.png)

PTB & Discord
![image](https://user-images.githubusercontent.com/29101687/163385378-0885bb9f-0022-41f6-9a12-5c934dee72ef.png)

So, canary only using placeholder attr of textarea to show the message in discord (using div and span) 
![image](https://user-images.githubusercontent.com/29101687/163385917-de0a35a1-455c-44fe-a56b-553225b5e864.png)

#### Experiment
I tried to insert a fake span in textarea using 
```js
var fakeSpan = document.createElement("span")
fakeSpan.style.display="none"
document.querySelector('[class^=textArea-]').appendChild(fakeSpan)
```
can solve this problem temporarily

#### Conclusion
I am not pretty sure whether only I meet this in Canary as @BobbyWibowo said "unable to replicate this till now, in Canary"
Although I disabled all of my plugins and themes in Canary, the Dom is still like the screenshot shown above. Hence, I think maybe the original Dom in Canary 124017 may like above.


Thanks a lot

**Comment by BobbyWibowo** [comment]
> **Canary 124017 (2c2001f)**

In which OS did you get this Canary build?
It might have been a temporary update to use `<textarea/>`

On my Windows boot, my Canary build is at **Canary 124157 (ad7bbc4)**, and it's using `<div></span></div>`, just like in Discord Stable

![image](https://user-images.githubusercontent.com/9364930/163526919-552f1061-e9ca-49a2-b279-e610cfe97e8b.png)

---

> Sorry, I miss the message that you also encountered this
> "encountering it on my end too"
> Therefore, it might caused by new version of canary.

Ah, I might have worded it wrong
I meant that I still had not encountered the issue, even in Canary, so I could not be sure if the workaround would work fine

**Comment by NawaNae** [comment]
> > **Canary 124017 (2c2001f)**
> 
> In which OS did you get this Canary build? It might have been a temporary update to use `<textarea/>`
> 
Windows 11 Home 21H2 22000.613
![image](https://user-images.githubusercontent.com/29101687/163558966-71df58af-f218-4837-b50e-f966637fb5b5.png)

Because my Canary version num (124017) seems to be lower than yours (124157).
I just tried to reinstall Canary, and the version num became Canary 124163 (9d74307) which is bigger than 124157 as well as 124017.
Still I get textarea in message sending box
![image](https://user-images.githubusercontent.com/29101687/163558842-af5d43e6-e1cb-41df-9ba7-ceb18ce9710a.png)

**Comment by BobbyWibowo** [comment]
I figured it out

Discord uses `<textarea/>` when this option below is turned off
![image](https://user-images.githubusercontent.com/9364930/163561604-06de5ea2-272c-4dda-85ce-e5f075450d88.png)

I will make a pull request containing a fix soon

**Comment by NawaNae** [comment]
Thanks a lot. Then I just trun this switch on for a temporary solution.
